name: flutter_templify
description: flutter_templify is a customizable CLI tool for managing Flutter app templates with YAML-based project definitions.
version: 0.1.2
homepage: https://github.com/micazi/flutter_templify

environment:
  sdk: ^3.5.3

dependencies:
  darted_cli: ^0.1.11

dev_dependencies:
  lints: ^4.0.0

executables:
  flutter_templify:
